"""empty message

Revision ID: 25084e841746
Revises: a0a871b436e7
Create Date: 2024-06-11 22:29:54.116878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25084e841746'
down_revision = 'a0a871b436e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
